import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle,
        AiFillLinkedin,
        AiFillYoutube} from 'react-icons/ai'
import { useState } from 'react'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : " "}>
      <Head>
        <title>Salim Nadji Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-orange-50'>By Nadji</h1>
              <ul className='flex justify-center space-x-5'>
                <li className='cursor-pointer text-xl dark:text-white'><BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)}/></li>
                <li>
                  <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-5 py-2 rounded-md font-burtons' href="#" >resume</a></li>
              </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-4xl text-teal-600 py-2 font-medium md:text-6xl'>Salim Nadji BELFEDHAL</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>FullStack and SAP developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-orange-50'>
              Freelancer offering services in programming, designing and all SAP technical consultant
              area, feel free to contact me for anything you need in my expertise area.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 text-gray-700 py-3'>
            <AiFillTwitterCircle className='dark:text-orange-50'/>
            <AiFillLinkedin className='dark:text-orange-50'/>
            <AiFillYoutube className='dark:text-orange-50'/>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} layout="fill" objectFit='cover'/>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-2xl py-3 dark:text-orange-50'>Service I Offer:</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-orange-50'>Since the beggening of my journey, i have worked for two small companies,
              the first one was apsolut where i was an SAP technical consultant in the procurement area,SLC,ARIBA and so on,
              after that i joined PayXpert as a Business Intelligence analyst, where i worked with ETL and created javascript 
              dashboards using D3 javascript library, since the pandemic i have been working remotely for 
            <span className='text-teal-500'> agencies</span>, consulted for <span className='text-teal-500'> startups</span> and collaborated
            with lot of talented workers from whom i learned a lot.
            </p>
            <p className='text-md text-gray-700 py-5 leading-8 dark:text-orange-50'>
              Actually, i am having lately free slots from which came the reason of offering this services.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={design} width="100" height="100"></Image>
              <h3 className='text-lg pb-2 pt-8 font-medium'>Beatiful Designs</h3>
              <p className='py-2'>Creating elegant designs suited for your needs following core design theory</p>
              <h4 className='py-4 text-teal-600'>Design tools i use</h4>
              <p className='py-1 text-gray-700'>Photoshop</p>
              <p className='py-1 text-gray-700'>Illustrator</p>
              <p className='py-1 text-gray-700'>Figma</p>
              <p className='py-1 text-gray-700'>Adobe XD</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} width="100" height="100"></Image>
              <h3 className='text-lg pb-2 pt-8 font-medium'>Good Coding</h3>
              <p className='py-2'>Creating elegant designs suited for your needs following core design theory</p>
              <h4 className='py-4 text-teal-600'>Design tools i use</h4>
              <p className='py-1 text-gray-700'>Photoshop</p>
              <p className='py-1 text-gray-700'>Illustrator</p>
              <p className='py-1 text-gray-700'>Figma</p>
              <p className='py-1 text-gray-700'>Adobe XD</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} width="100" height="100"></Image>
              <h3 className='text-lg pb-2 pt-8 font-medium'>Professional Consulting</h3>
              <p className='py-2'>Creating elegant designs suited for your needs following core design theory</p>
              <h4 className='py-4 text-teal-600'>Design tools i use</h4>
              <p className='py-1 text-gray-700'>Photoshop</p>
              <p className='py-1 text-gray-700'>Illustrator</p>
              <p className='py-1 text-gray-700'>Figma</p>
              <p className='py-1 text-gray-700'>Adobe XD</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-2xl py-3 dark:text-white'>Portofolio</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-orange-50'>Since the beggening of my journey, i have worked for two small companies,
              the first one was apsolut where i was an SAP technical consultant in the procurement area,SLC,ARIBA and so on,
              after that i joined PayXpert as a Business Intelligence analyst, where i worked with ETL and created javascript 
              dashboards using D3 javascript library, since the pandemic i have been working remotely for 
            <span className='text-teal-500'> agencies</span>, consulted for <span className='text-teal-500'> startups</span> and collaborated
            with lot of talented workers from whom i learned a lot.
            </p>
            <p className='text-md text-gray-700 py-5 leading-8 dark:text-orange-50'>
              Actually, i am having lately free slots from which came the reason of offering this services.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover' width='100%' height='100%' layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className='rounded-lg object-cover' width='100%' height='100%' layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover' width='100%' height='100%' layout='responsive'/>
            </div> 
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className='rounded-lg object-cover' width='100%' height='100%' layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-cover' width='100%' height='100%' layout='responsive'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-cover' width='100%' height='100%' layout='responsive'/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
